Refatora o repositório para os padrões utilizados pela comunidade

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -1,100 +1,157 @@
-name: 'PortalBrasil: Intranet - Backend CI'
+name: "PortalBrasil: Intranet - Backend"
 
 on:
   workflow_call:
-  workflow_dispatch:
-
-env:
-  IMAGE_NAME_PREFIX: ghcr.io/plonegovbr/portalbrasil-intranet
-  IMAGE_NAME_SUFFIX: backend
-  PYTHON_VERSION: "3.11"
+    inputs:
+      base-tag:
+        required: true
+        type: string
+      image-name-prefix:
+        required: true
+        type: string
+      image-name-suffix:
+        required: true
+        type: string
+      python-version:
+        required: true
+        type: string
+      pb-version:
+        required: true
+        type: string
 
 defaults:
   run:
-    working-directory: ./backend
+    working-directory: backend
 
 jobs:
 
-  config:
+  lint:
     runs-on: ubuntu-latest
-    outputs:
-      BASE_TAG: ${{ steps.vars.outputs.BASE_TAG }}
-      PLONE_VERSION: ${{ steps.vars.outputs.PLONE_VERSION }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
 
-      - name: Set Env Vars
-        id: vars
-        run: |
-          echo "PLONE_VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
-          echo 'BASE_TAG=sha-'$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
+        - name: Checkout
+          uses: actions/checkout@v4
 
-      - name: Test vars
-        run: |
-          echo 'BASE_TAG=${{ steps.vars.outputs.BASE_TAG }}'
-          echo 'PLONE_VERSION=${{ steps.vars.outputs.PLONE_VERSION }}'
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: true
 
-  code-quality:
-    runs-on: ubuntu-latest
-    needs:
-      - config
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
+        - name: Check formatting
+          if: ${{ success() || failure() }}
+          id: ruff-format
+          run: uvx ruff@latest format --diff
 
-      - name: Install hatch
-        run: pipx install hatch
+        - name: Check lint
+          if: ${{ success() || failure() }}
+          id: ruff-lint
+          run: uvx ruff@latest check --diff
 
-      - name: Generate Constraints file
-        run: |
-          make constraints-mxdev.txt
-          pipx run mxdev -c mx.ini
+        - name: Check XML / ZCML
+          if: ${{ success() || failure() }}
+          id: zpretty
+          run: uvx zpretty@latest --check src
 
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-          cache: 'pip'
+        - name: Check Package Metadata
+          if: ${{ success() || failure() }}
+          id: pyroma
+          run: uvx pyroma@latest -d .
 
-      - name: "Install Environment"
-        run: hatch env create
+        - name: Check Python Versions
+          if: ${{ success() || failure() }}
+          id: py-versions
+          run: uvx check-python-versions@latest .
 
-      - name: "Run checks"
-        run: hatch run lint
+        - name: Report
+          if: ${{ success() || failure() }}
+          run: |
+            echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+            echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+            echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+            echo '| Format | ${{ steps.ruff-format.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Lint | ${{ steps.ruff-lint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| XML / ZCML | ${{ steps.zpretty.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Package Metadata | ${{ steps.pyroma.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Python Versions | ${{ steps.py-versions.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
 
   test:
     runs-on: ubuntu-latest
-    needs:
-      - config
+    env:
+      PYTHON_VERSION: ${{ inputs.python-version }}
+      PLONE_VERSION: ${{ inputs.pb-version }}
     steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
 
-      - name: Install hatch
-        run: pipx install hatch
+        - name: Checkout
+          uses: actions/checkout@v4
 
-      - name: Generate Constraints file
-        run: |
-          make constraints-mxdev.txt
-          pipx run mxdev -c mx.ini
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: false
 
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-          cache: 'pip'
+        - name: Restore uv cache
+          uses: actions/cache@v4
+          with:
+            path: ${{ env.UV_CACHE_DIR }}
+            key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}-${{ hashFiles('pyproject.toml') }}
+            restore-keys: |
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}-${{ hashFiles('pyproject.toml') }}
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}
 
-      - name: "Install Environment"
-        run: hatch env create
+        - name: Install Plone and package
+          run: make install
 
-      - name: "Test Codebase"
-        run: hatch run test
+        - name: Run tests
+          run: make test
 
-  release:
+  coverage:
     runs-on: ubuntu-latest
     needs:
-      - config
-      - code-quality
       - test
+    steps:
+        - name: Checkout
+          uses: actions/checkout@v4
+
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: false
+
+        - name: Restore uv cache
+          uses: actions/cache@v4
+          with:
+            path: /tmp/.uv-cache
+            key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}-${{ hashFiles('pyproject.toml') }}
+            restore-keys: |
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}-${{ hashFiles('pyproject.toml') }}
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.pb-version }}
+
+        - name: Install Plone and package
+          run: make install
+
+        - name: Run tests
+          run: make test-coverage
+
+        - name: Report Coverage
+          run: |
+            echo "# Coverage Report" >> $GITHUB_STEP_SUMMARY
+            echo "$(uv run coverage report --format markdown)" >> $GITHUB_STEP_SUMMARY
+
+  release-backend:
+    runs-on: ubuntu-latest
+    needs:
+      - lint
+      - coverage
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - image-name-suffix: "backend"
+            dockerfile: "backend/Dockerfile"
+
     permissions:
       contents: read
       packages: write
@@ -109,14 +166,17 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: |
-            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}
+            ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}:latest
+            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}:${{ inputs.base-tag }}
           flavor:
             latest=false
           tags: |
             type=ref,event=branch
             type=sha
+            type=pep440,pattern={{version}}
+            type=pep440,pattern={{major}}.{{minor}}
+            type=pep440,pattern={{major}}
             type=raw,value=latest,enable={{is_default_branch}}
 
       - name: Set up QEMU
@@ -132,43 +192,81 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build and push
-        uses: docker/build-push-action@v5
+      - name: Build and push ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64
-          context: backend
-          file: backend/Dockerfile
+          context: backend/
+          file: ${{ matrix.dockerfile }}
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
-            PLONE_VERSION=${{ needs.config.outputs.PLONE_VERSION }}
+            IMAGE_TAG=${{ inputs.base-tag }}
+            SEED=${{ github.run_id }}
+            PB_VERSION=${{ inputs.pb-version }}
+
+  release-demo:
+    runs-on: ubuntu-latest
+    needs:
+      - release-backend
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - image-name-suffix: "demo"
+            dockerfile: "backend/Dockerfile.demo"
+
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v4
 
       - name: Docker meta
-        id: meta-demo
+        id: meta
         uses: docker/metadata-action@v5
         with:
           images: |
-            ${{ env.IMAGE_NAME_PREFIX }}-demo
+            ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ env.IMAGE_NAME_PREFIX }}-demo:latest
+            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}:${{ inputs.base-tag }}
           flavor:
             latest=false
           tags: |
             type=ref,event=branch
             type=sha
+            type=pep440,pattern={{version}}
+            type=pep440,pattern={{major}}.{{minor}}
+            type=pep440,pattern={{major}}
             type=raw,value=latest,enable={{is_default_branch}}
 
-      - name: Build and push demo
-        uses: docker/build-push-action@v5
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push ${{ inputs.image-name-prefix }}-${{ matrix.image-name-suffix }}
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64
-          context: backend
-          file: backend/Dockerfile.demo
-          load: true
+          context: backend/
+          file: ${{ matrix.dockerfile }}
           push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta-demo.outputs.tags }}
-          labels: ${{ steps.meta-demo.outputs.labels }}
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
           build-args: |
+            IMAGE_TAG=${{ inputs.base-tag }}
             SEED=${{ github.run_id }}
-            IMAGE_TAG=${{ needs.config.outputs.BASE_TAG }}
+            PB_VERSION=${{ inputs.pb-version }}
